# Generated by Django 4.0 on 2022-07-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_screenoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenoption',
            name='ad_rating',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='comp_rating_max',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='comp_rating_min',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='eps_rating_max',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='eps_rating_min',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='ind_group_rs_rating',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='rs_rating_max',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='rs_rating_min',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='screenoption',
            name='smr_rating',
        ),
    ]
