# Generated by Django 4.0 on 2022-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_screenoption_ad_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenoption',
            name='ad_rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='comp_rating_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='comp_rating_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='eps_rating_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='eps_rating_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='ind_group_rs_rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='rs_rating_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='rs_rating_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='screen_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='smr_rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
