# Generated by Django 4.0.6 on 2022-07-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_screenoption_etf_screenoption_headquarters_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenoption',
            name='ibd_50',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='ibd_article_lst_2_y',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='new_ceo_in_lst_12_m',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
