# Generated by Django 4.0 on 2022-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_screenoption_ad_rating_screenoption_comp_rating_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenoption',
            name='adr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='after_tax_mrgn_acce_lst_3_q',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='cur_d_vol_grt_pre_10_d',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='cur_d_vol_grt_pre_20_d',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='cur_d_vol_grt_pre_5_d',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='d_10_d_21_d_50',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='d_50_d_150_d_200',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='eps_chg_lst_rpt_q_eps_chg_lst_q_3_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='eps_grow_rate_lst_3y_5y_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='eps_lst_rpty_4y_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='eps_trailing_q_4_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='eps_trailing_q_4_lst_y_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='erns_acce_lst_q_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='etf',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='etf_closed_end_fund',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='ibd_50',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='ibd_85',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='ibd_article_lst_2_y',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='ibd_big_cap_20',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='ibd_new_america',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='new_ceo_in_lst_12_m',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='opr_sys_ids_median_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='options',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='p_e_avg_5y_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='profile_mrgn_ids_median_is_bigger',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='sales_acc_lst_2_q',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='sales_acc_lst_3_q',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='tot_lia_tot_assn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
