# Generated by Django 4.0 on 2022-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_screenoption_adr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenoption',
            name='erns_dued_max',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='erns_dued_min',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='erns_lst_rpt_date_max',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenoption',
            name='erns_lst_rpt_date_min',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
