# Generated by Django 4.0.6 on 2022-07-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_screenoption_ibd_50_screenoption_ibd_article_lst_2_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenoption',
            name='ibd_85',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='ibd_big_cap_20',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenoption',
            name='ibd_new_america',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
