# Generated by Django 4.0.6 on 2022-07-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_screenoption_ibd_85_screenoption_ibd_big_cap_20_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlay',
            fields=[
                ('ticker_symbol', models.OneToOneField(db_column='ticker_symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.tickers')),
                ('date_populated', models.DateField(blank=True, null=True)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('third', models.IntegerField()),
                ('fourth', models.IntegerField()),
                ('fifth', models.IntegerField()),
                ('sixth', models.IntegerField()),
                ('seventh', models.IntegerField()),
                ('eighth', models.IntegerField()),
            ],
            options={
                'db_table': 'power_play',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('ticker_symbol', models.OneToOneField(db_column='ticker_symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.tickers')),
                ('date_populated', models.DateField(blank=True, null=True)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('third', models.IntegerField()),
                ('fourth', models.IntegerField()),
                ('fifth', models.IntegerField()),
                ('sixth', models.IntegerField()),
                ('seventh', models.IntegerField()),
                ('eighth', models.IntegerField()),
            ],
            options={
                'db_table': 'trend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendWide',
            fields=[
                ('ticker_symbol', models.OneToOneField(db_column='ticker_symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.tickers')),
                ('date_populated', models.DateField(blank=True, null=True)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('third', models.IntegerField()),
                ('fourth', models.IntegerField()),
                ('fifth', models.IntegerField()),
                ('sixth', models.IntegerField()),
                ('seventh', models.IntegerField()),
            ],
            options={
                'db_table': 'trend_wide',
                'managed': False,
            },
        ),
    ]
