import React, { useState } from "react";

import { connect } from "react-redux";

import {
    Box,
    Grid,
} from '@mui/material';

import Category from "./Category";
import Criteria from "./Criteria";
import Summary from "./Summary";

import { makeStyles, useTheme } from "@mui/styles";

const useStyles = makeStyles((theme) => ({
    root : {
        
    }
}))

const ScreenOption = (props) => {
    const classes = useStyles();
    const theme = useTheme() ;

    const {
        selectedScreenList,
        formData,
        inserFormtData
    } = props;

    const [ selectedItem, setSelectedItem ] = useState('smart') ;
    const [ stateFormData, setStateFormData ] = React.useState({
        screen_id : selectedScreenList,
        eps_rating_min : 0,
        eps_rating_max : 0,
        rs_rating_min : 0,
        rs_rating_min : 0,
        rs_rating_max : 0,
        smr_rating : '',
        ad_rating : '',
        comp_rating_min : 0,
        comp_rating_max : 0,
        ind_group_rs_rating : '',
        erns_lst_rpt_date_min : new Date().toISOString().substring(0, 10),
        erns_lst_rpt_date_max : new Date().toISOString().substring(0, 10),
        erns_dued_min : new Date().toISOString().substring(0, 10),
        erns_dued_max : new Date().toISOString().substring(0, 10),
        eps_chg_lst_rpt_q_min : 0,
        eps_chg_lst_rpt_q_max : 0,
        eps_chg_q_1_min : 0,
        eps_chg_q_1_max : 0,
        erns_acce_lst_q_3 : "no",
        erns_stability_min : 0,
        erns_stability_max : 0,
        eps_chg_q_2_min : 0,
        eps_chg_q_2_max : 0,
        eps_chg_q_3_min : 0,
        eps_chg_q_3_max : 0,
        eps_chg_lst_rpt_q_eps_chg_lst_q_3_is_bigger : "no",
        avg_eps_chg_lst_q_2_min : 0,
        avg_eps_chg_lst_q_2_max : 0,
        avg_eps_chg_lst_q_3_min : 0,
        avg_eps_chg_lst_q_3_max : 0,
        avg_eps_chg_lst_q_4_min : 0,
        avg_eps_chg_lst_q_4_max : 0,
        avg_eps_chg_lst_q_5_min : 0,
        avg_eps_chg_lst_q_5_max : 0,
        avg_eps_chg_lst_q_6_min : 0,
        avg_eps_chg_lst_q_6_max : 0,
        eps_trailing_q_4_min : 0,
        eps_trailing_q_4_max : 0,
        eps_trailing_q_4_is_bigger : "no",
        eps_trailing_q_4_lst_y_is_bigger : "no",
        eps_chg_lst_rpty_vs_1y_ago_min : 0,
        eps_chg_lst_rpty_vs_1y_ago_max : 0,
        eps_chg_lst_rpty_vs_2y_ago_min : 0,
        eps_chg_lst_rpty_vs_2y_ago_max : 0,
        eps_chg_lst_y_min : 0,
        eps_chg_lst_y_max : 0,
        eps_grow_rate_lst_3y_min : 0,
        eps_grow_rate_lst_3y_max : 0,
        eps_grow_rate_lst_5y_min : 0,
        eps_grow_rate_lst_5y_max : 0,
        eps_grow_rate_lst_3y_5y_is_bigger : "no",
        eps_grow_rate_lst_5y_percent_rnk_min : 0,
        eps_grow_rate_lst_5y_percent_rnk_max : 0,
        eps_grow_rate_projected_sus_growth_min : 0,
        eps_grow_rate_projected_sus_growth_max : 0,
        eps_lst_rpty_min : 0,
        eps_lst_rpty_max : 0,
        eps_1y_ago_min : 0,
        eps_1y_ago_max : 0,
        eps_2y_ago_min : 0,
        eps_2y_ago_max : 0,
        eps_3y_ago_min : 0,
        eps_3y_ago_max : 0,
        eps_4y_ago_min : 0,
        eps_4y_ago_max : 0,
        eps_5y_ago_min : 0,
        eps_5y_ago_max : 0,
        eps_6y_ago_min : 0,
        eps_6y_ago_max : 0,
        eps_lst_rpty_4y_is_bigger : "no",
        eps_est_erns_surp_min : 0,
        eps_est_erns_surp_max : 0,
        eps_est_chg_next_q_min : 0,
        eps_est_chg_next_q_max : 0,
        eps_est_chg_cur_y_min : 0,
        eps_est_chg_cur_y_max : 0,
        eps_est_chg_1y_forward_vs_min : 0,
        eps_est_chg_1y_forward_vs_max : 0,
        sales_chg_lst_rpt_q_min : 0,
        sales_chg_lst_rpt_q_max : 0,
        avg_sales_chg_lst_2_q_min : 0,
        avg_sales_chg_lst_2_q_max : 0,
        avg_sales_chg_lst_3_q_min : 0,
        avg_sales_chg_lst_3_q_max : 0,
        avg_sales_chg_lst_4_q_min : 0,
        avg_sales_chg_lst_4_q_max : 0,
        avg_sales_chg_lst_5_q_min : 0,
        avg_sales_chg_lst_5_q_max : 0,
        avg_sales_chg_lst_6_q_min : 0,
        avg_sales_chg_lst_6_q_max : 0,
        sales_acc_lst_2_q : 'no',
        sales_acc_lst_3_q : 'no',
        sales_chg_lst_rpt_y_min : 0,
        sales_chg_lst_rpt_y_max : 0,
        sales_growth_rate_lst_3_y_min : 0,
        sales_growth_rate_lst_3_y_max : 0,
        sales_growth_rate_lst_5_y_min : 0,
        sales_growth_rate_lst_5_y_max : 0,
        tot_ann_sales_lst_rpt_y_min : 0,
        tot_ann_sales_lst_rpt_y_max : 0,
        company_ids_g_r_min : 0,
        company_ids_g_r_max : 0,
        industry_g_n : [],
        broad_sectors : [],
        shares_outstanding_min : 0,
        shares_outstanding_max : 0,
        shares_in_float_min : 0,
        shares_in_float_max : 0,
        market_capitialization_min : 0,
        market_capitialization_max : 0,
        enterprise_value_min : 0,
        enterprise_value_max : 0,
        sponsorship_rating : '',
        funds_min : 0,
        funds_max : 0,
        funds_increase_min : 0,
        funds_increase_max : 0,
        number_of_fund_min : 0,
        number_of_fund_max : 0,
        management_min : 0,
        management_max : 0,
        institutional_ownership : 'no',
        price_min : 0,
        price_max : 0,
        price_vs_52_week_high_min : 0,
        price_vs_52_week_high_max : 0,
        price_chg_cur_d_min : 0,
        price_chg_cur_d_max : 0,
        price_chg_min : 0,
        price_chg_max : 0,
        price_chg_cur_w_min : 0,
        price_chg_cur_w_max : 0,
        price_chg_lst_m_min : 0,
        price_chg_lst_m_max : 0,
        price_chg_lst_3_m_min : 0,
        price_chg_lst_3_m_max : 0,
        price_chg_lst_6_m_min : 0,
        price_chg_lst_6_m_max : 0,
        price_chg_lst_12_m_min : 0,
        price_chg_lst_12_m_max : 0,
        price_chg_y_to_d_min : 0,
        price_chg_y_to_d_max : 0,
        price_chg_sp_500_lst26w_min : 0,
        price_chg_sp_500_lst26w_max : 0,
        weekly_closing_range_min : 0,
        weekly_closing_range_max : 0,
        daily_closing_range_min : 0,
        daily_closing_range_max : 0,
        price_vs_10_d_min : 0,
        price_vs_10_d_max : 0,
        price_vs_21_d_min : 0,
        price_vs_21_d_max : 0,
        price_vs_50_d_min : 0,
        price_vs_50_d_max : 0,
        price_vs_150_d_min : 0,
        price_vs_150_d_max : 0,
        price_vs_200_d_min : 0,
        price_vs_200_d_max : 0,
        d_10_d_21_d_50 : 'no',
        d_50_d_150_d_200 : 'no',
        vol_50_d_avg_min : 0,
        vol_50_d_avg_max : 0,
        vol_Chg_50_d_avg_min : 0,
        vol_Chg_50_d_avg_max : 0,
        w_vol_chg_10_w_avg_min : 0,
        w_vol_chg_10_w_avg_max : 0,
        cur_d_vol_grt_pre_5_d : 'no',
        cur_d_vol_grt_pre_10_d : 'no',
        cur_d_vol_grt_pre_20_d : 'no',
        vol_int_min : 0,
        vol_int_max : 0,
        up_down_vol_rat_min : 0,
        up_down_vol_rat_max : 0,
        vol_50_d_avg_dol_1000s_min : 0,
        vol_50_d_avg_dol_1000s_max : 0,
        rs_line_new_high : 'no',
        rs_line_new_low : 'no',
        rs_rating_3_m_min : 0,
        rs_rating_3_m_max : 0,
        rs_rating_6_m_min : 0,
        rs_rating_6_m_max : 0,
        timeliness_rating : '',
        alpha_min : 0,
        alpha_max : 0,
        beta_min : 0,
        beta_max : 0,
        avg_true_range_30_d_min : 0,
        avg_true_range_30_d_max : 0,
        davidend_yield_min : 0,
        davidend_yield_max : 0,
        after_tax_mrgn_acce_lst_3_q : 'no',
        pre_tax_mrgn_lst_rpty_min : 0,
        pre_tax_mrgn_lst_rpty_max : 0,
        after_tax_mrgn_lst_rpt_q_min : 0,
        after_tax_mrgn_lst_rpt_q_max : 0,
        after_tax_mrgn_avg_lst_q_2_min : 0,
        after_tax_mrgn_avg_lst_q_2_max : 0,
        after_tax_mrgn_avg_lst_q_3_min : 0,
        after_tax_mrgn_avg_lst_q_3_max : 0,
        after_tax_mrgn_avg_lst_q_4_min : 0,
        after_tax_mrgn_avg_lst_q_4_max : 0,
        after_tax_mrgn_avg_lst_q_5_min : 0,
        after_tax_mrgn_avg_lst_q_5_max : 0,
        after_tax_mrgn_avg_lst_q_6_min : 0,
        after_tax_mrgn_avg_lst_q_6_max : 0,
        opr_sys_ids_median_is_bigger : 'no',
        profile_mrgn_ids_median_is_bigger : 'no',
        p_e_current_min : 0,
        p_e_current_max : 0,
        p_e_est_min : 0,
        p_e_est_max : 0,
        p_e_vs_sp_500_min : 0,
        p_e_vs_sp_500_max : 0,
        p_e_percent_rnk_min : 0,
        p_e_percent_rnk_max : 0,
        p_e_percent_rnk_in_grp_min : 0,
        p_e_percent_rnk_in_grp_max : 0,
        p_e_avg_5y_is_bigger : 'no',
        peg_min : 0,
        peg_max : 0,
        peg_divid_adj_min : 0,
        peg_divid_adj_max : 0,
        cf_v_eps_diff_lst_rpt_q_min : 0,
        cf_v_eps_diff_lst_rpt_q_max : 0,
        cf_v_eps_diff_lst_rpt_y_min : 0,
        cf_v_eps_diff_lst_rpt_y_max : 0,
        roe_5y_avg_min : 0,
        roe_5y_avg_max : 0,
        debit_lst_rpt_y_min : 0,
        debit_lst_rpt_y_max : 0,
        current_ratio_min : 0,
        current_ratio_max : 0,
        price_to_sales_min : 0,
        price_to_sales_max : 0,
        price_to_book_value_min : 0,
        price_to_book_value_max : 0,
        price_to_cash_flow_min : 0,
        price_to_cash_flow_max : 0,
        epr_val_free_cash_flow_min : 0,
        epr_val_free_cash_flow_max : 0,
        long_term_debit_work_cap_min : 0,
        long_term_debit_work_cap_max : 0,
        tot_lia_tot_assn : 'no',
        exchange : [],
        adr : 'no',
        etf_closed_end_fund : 'no',
        etf : 'no',
        options : 'no',
        ipo_date_min : new Date().toISOString().substring(0, 10),
        ipo_date_max : new Date().toISOString().substring(0, 10),
        incorporation_date_min : new Date().toISOString().substring(0, 10),
        incorporation_date_max : new Date().toISOString().substring(0, 10),
        headquarters_city : [],
        new_ceo_in_lst_12_m : 'no',
        ibd_article_lst_2_y : 'no',
        ibd_50 : 'no',
        ibd_new_america : 'no',
        ibd_85 : 'no',
        ibd_big_cap_20 : 'no',
    })

    const [oldStateFormData, setOldStateFormData] = React.useState({
        screen_id : selectedScreenList,
        eps_rating_min : 0,
        eps_rating_max : 0,
        rs_rating_min : 0,
        rs_rating_max : 0,
        smr_rating : '',
        ad_rating : '',
        comp_rating_min : 0,
        comp_rating_max : 0,
        ind_group_rs_rating : '',
        erns_lst_rpt_date_min : new Date().toISOString().substring(0, 10),
        erns_lst_rpt_date_max : new Date().toISOString().substring(0, 10),
        erns_dued_min : new Date().toISOString().substring(0, 10),
        erns_dued_max : new Date().toISOString().substring(0, 10),
        eps_chg_lst_rpt_q_min : 0,
        eps_chg_lst_rpt_q_max : 0,
        eps_chg_q_1_min : 0,
        eps_chg_q_1_max : 0,
        erns_acce_lst_q_3 : "no",
        erns_stability_min : 0,
        erns_stability_max : 0,
        eps_chg_q_2_min : 0,
        eps_chg_q_2_max : 0,
        eps_chg_q_3_min : 0,
        eps_chg_q_3_max : 0,
        eps_chg_lst_rpt_q_eps_chg_lst_q_3_is_bigger : "no",
        avg_eps_chg_lst_q_2_min : 0,
        avg_eps_chg_lst_q_2_max : 0,
        avg_eps_chg_lst_q_3_min : 0,
        avg_eps_chg_lst_q_3_max : 0,
        avg_eps_chg_lst_q_4_min : 0,
        avg_eps_chg_lst_q_4_max : 0,
        avg_eps_chg_lst_q_5_min : 0,
        avg_eps_chg_lst_q_5_max : 0,
        avg_eps_chg_lst_q_6_min : 0,
        avg_eps_chg_lst_q_6_max : 0,
        eps_trailing_q_4_min : 0,
        eps_trailing_q_4_max : 0,
        eps_trailing_q_4_is_bigger : "no",
        eps_trailing_q_4_lst_y_is_bigger : "no",
        eps_chg_lst_rpty_vs_1y_ago_min : 0,
        eps_chg_lst_rpty_vs_1y_ago_max : 0,
        eps_chg_lst_rpty_vs_2y_ago_min : 0,
        eps_chg_lst_rpty_vs_2y_ago_max : 0,
        eps_chg_lst_y_min : 0,
        eps_chg_lst_y_max : 0,
        eps_grow_rate_lst_3y_min : 0,
        eps_grow_rate_lst_3y_max : 0,
        eps_grow_rate_lst_5y_min : 0,
        eps_grow_rate_lst_5y_max : 0,
        eps_grow_rate_lst_3y_5y_is_bigger : "no",
        eps_grow_rate_lst_5y_percent_rnk_min : 0,
        eps_grow_rate_lst_5y_percent_rnk_max : 0,
        eps_grow_rate_projected_sus_growth_min : 0,
        eps_grow_rate_projected_sus_growth_max : 0,
        eps_lst_rpty_min : 0,
        eps_lst_rpty_max : 0,
        eps_1y_ago_min : 0,
        eps_1y_ago_max : 0,
        eps_2y_ago_min : 0,
        eps_2y_ago_max : 0,
        eps_3y_ago_min : 0,
        eps_3y_ago_max : 0,
        eps_4y_ago_min : 0,
        eps_4y_ago_max : 0,
        eps_5y_ago_min : 0,
        eps_5y_ago_max : 0,
        eps_6y_ago_min : 0,
        eps_6y_ago_max : 0,
        eps_lst_rpty_4y_is_bigger : "no",
        eps_est_erns_surp_min : 0,
        eps_est_erns_surp_max : 0,
        eps_est_chg_next_q_min : 0,
        eps_est_chg_next_q_max : 0,
        eps_est_chg_cur_y_min : 0,
        eps_est_chg_cur_y_max : 0,
        eps_est_chg_1y_forward_vs_min : 0,
        eps_est_chg_1y_forward_vs_max : 0,
        sales_chg_lst_rpt_q_min : 0,
        sales_chg_lst_rpt_q_max : 0,
        avg_sales_chg_lst_2_q_min : 0,
        avg_sales_chg_lst_2_q_max : 0,
        avg_sales_chg_lst_3_q_min : 0,
        avg_sales_chg_lst_3_q_max : 0,
        avg_sales_chg_lst_4_q_min : 0,
        avg_sales_chg_lst_4_q_max : 0,
        avg_sales_chg_lst_5_q_min : 0,
        avg_sales_chg_lst_5_q_max : 0,
        avg_sales_chg_lst_6_q_min : 0,
        avg_sales_chg_lst_6_q_max : 0,
        sales_acc_lst_2_q : 'no',
        sales_acc_lst_3_q : 'no',
        sales_chg_lst_rpt_y_min : 0,
        sales_chg_lst_rpt_y_max : 0,
        sales_growth_rate_lst_3_y_min : 0,
        sales_growth_rate_lst_3_y_max : 0,
        sales_growth_rate_lst_5_y_min : 0,
        sales_growth_rate_lst_5_y_max : 0,
        tot_ann_sales_lst_rpt_y_min : 0,
        tot_ann_sales_lst_rpt_y_max : 0,
        company_ids_g_r_min : 0,
        company_ids_g_r_max : 0,
        industry_g_n : [],
        broad_sectors : [],
        shares_outstanding_min : 0,
        shares_outstanding_max : 0,
        shares_in_float_min : 0,
        shares_in_float_max : 0,
        market_capitialization_min : 0,
        market_capitialization_max : 0,
        enterprise_value_min : 0,
        enterprise_value_max : 0,
        sponsorship_rating : '',
        funds_min : 0,
        funds_max : 0,
        funds_increase_min : 0,
        funds_increase_max : 0,
        number_of_fund_min : 0,
        number_of_fund_max : 0,
        management_min : 0,
        management_max : 0,
        institutional_ownership : 'no',
        price_min : 0,
        price_max : 0,
        price_vs_52_week_high_min : 0,
        price_vs_52_week_high_max : 0,
        price_chg_cur_d_min : 0,
        price_chg_cur_d_max : 0,
        price_chg_min : 0,
        price_chg_max : 0,
        price_chg_cur_w_min : 0,
        price_chg_cur_w_max : 0,
        price_chg_lst_m_min : 0,
        price_chg_lst_m_max : 0,
        price_chg_lst_3_m_min : 0,
        price_chg_lst_3_m_max : 0,
        price_chg_lst_6_m_min : 0,
        price_chg_lst_6_m_max : 0,
        price_chg_lst_12_m_min : 0,
        price_chg_lst_12_m_max : 0,
        price_chg_y_to_d_min : 0,
        price_chg_y_to_d_max : 0,
        price_chg_sp_500_lst26w_min : 0,
        price_chg_sp_500_lst26w_max : 0,
        weekly_closing_range_min : 0,
        weekly_closing_range_max : 0,
        daily_closing_range_min : 0,
        daily_closing_range_max : 0,
        price_vs_10_d_min : 0,
        price_vs_10_d_max : 0,
        price_vs_21_d_min : 0,
        price_vs_21_d_max : 0,
        price_vs_50_d_min : 0,
        price_vs_50_d_max : 0,
        price_vs_150_d_min : 0,
        price_vs_150_d_max : 0,
        price_vs_200_d_min : 0,
        price_vs_200_d_max : 0,
        d_10_d_21_d_50 : 'no',
        d_50_d_150_d_200 : 'no',
        vol_50_d_avg_min : 0,
        vol_50_d_avg_max : 0,
        vol_Chg_50_d_avg_min : 0,
        vol_Chg_50_d_avg_max : 0,
        w_vol_chg_10_w_avg_min : 0,
        w_vol_chg_10_w_avg_max : 0,
        cur_d_vol_grt_pre_5_d : 'no',
        cur_d_vol_grt_pre_10_d : 'no',
        cur_d_vol_grt_pre_20_d : 'no',
        vol_int_min : 0,
        vol_int_max : 0,
        up_down_vol_rat_min : 0,
        up_down_vol_rat_max : 0,
        vol_50_d_avg_dol_1000s_min : 0,
        vol_50_d_avg_dol_1000s_max : 0,
        rs_line_new_high : 'no',
        rs_line_new_low : 'no',
        rs_rating_3_m_min : 0,
        rs_rating_3_m_max : 0,
        rs_rating_6_m_min : 0,
        rs_rating_6_m_max : 0,
        timeliness_rating : '',
        alpha_min : 0,
        alpha_max : 0,
        beta_min : 0,
        beta_max : 0,
        avg_true_range_30_d_min : 0,
        avg_true_range_30_d_max : 0,
        davidend_yield_min : 0,
        davidend_yield_max : 0,
        after_tax_mrgn_acce_lst_3_q : 'no',
        pre_tax_mrgn_lst_rpty_min : 0,
        pre_tax_mrgn_lst_rpty_max : 0,
        after_tax_mrgn_lst_rpt_q_min : 0,
        after_tax_mrgn_lst_rpt_q_max : 0,
        after_tax_mrgn_avg_lst_q_2_min : 0,
        after_tax_mrgn_avg_lst_q_2_max : 0,
        after_tax_mrgn_avg_lst_q_3_min : 0,
        after_tax_mrgn_avg_lst_q_3_max : 0,
        after_tax_mrgn_avg_lst_q_4_min : 0,
        after_tax_mrgn_avg_lst_q_4_max : 0,
        after_tax_mrgn_avg_lst_q_5_min : 0,
        after_tax_mrgn_avg_lst_q_5_max : 0,
        after_tax_mrgn_avg_lst_q_6_min : 0,
        after_tax_mrgn_avg_lst_q_6_max : 0,
        opr_sys_ids_median_is_bigger : 'no',
        profile_mrgn_ids_median_is_bigger : 'no',
        p_e_current_min : 0,
        p_e_current_max : 0,
        p_e_est_min : 0,
        p_e_est_max : 0,
        p_e_vs_sp_500_min : 0,
        p_e_vs_sp_500_max : 0,
        p_e_percent_rnk_min : 0,
        p_e_percent_rnk_max : 0,
        p_e_percent_rnk_in_grp_min : 0,
        p_e_percent_rnk_in_grp_max : 0,
        p_e_avg_5y_is_bigger : 'no',
        peg_min : 0,
        peg_max : 0,
        peg_divid_adj_min : 0,
        peg_divid_adj_max : 0,
        cf_v_eps_diff_lst_rpt_q_min : 0,
        cf_v_eps_diff_lst_rpt_q_max : 0,
        cf_v_eps_diff_lst_rpt_y_min : 0,
        cf_v_eps_diff_lst_rpt_y_max : 0,
        roe_5y_avg_min : 0,
        roe_5y_avg_max : 0,
        debit_lst_rpt_y_min : 0,
        debit_lst_rpt_y_max : 0,
        current_ratio_min : 0,
        current_ratio_max : 0,
        price_to_sales_min : 0,
        price_to_sales_max : 0,
        price_to_book_value_min : 0,
        price_to_book_value_max : 0,
        price_to_cash_flow_min : 0,
        price_to_cash_flow_max : 0,
        epr_val_free_cash_flow_min : 0,
        epr_val_free_cash_flow_max : 0,
        long_term_debit_work_cap_min : 0,
        long_term_debit_work_cap_max : 0,
        tot_lia_tot_assn : 'no',
        exchange : [],
        adr : 'no',
        etf_closed_end_fund : 'no',
        etf : 'no',
        options : 'no',
        ipo_date_min : new Date().toISOString().substring(0, 10),
        ipo_date_max : new Date().toISOString().substring(0, 10),
        incorporation_date_min : new Date().toISOString().substring(0, 10),
        incorporation_date_max : new Date().toISOString().substring(0, 10),
        headquarters_city : [],
        new_ceo_in_lst_12_m : 'no',
        ibd_article_lst_2_y : 'no',
        ibd_50 : 'no',
        ibd_new_america : 'no',
        ibd_85 : 'no',
        ibd_big_cap_20 : 'no',
    })

    React.useEffect(() => {
        if( formData ){
            if(formData.length != 0 ){
                
                let industry_g_n = formData.industry_g_n
                let result = industry_g_n.replace( /'/g, '"')
                let _industry_g_n = JSON.parse( result )

                let exchange = formData.exchange
                result = exchange.replace( /'/g, '"')
                let _exchange = JSON.parse( result )

                let headquarters_city = formData.headquarters_city
                result = headquarters_city.replace( /'/g, '"')
                let _headquarters_city = JSON.parse( result )
                
                let broad_sectors = formData.broad_sectors
                result = broad_sectors.replace( /'/g, '"')
                let _broad_sectors = JSON.parse( result )

                setStateFormData( { 
                    ...formData, 
                    industry_g_n: _industry_g_n,
                    exchange: _exchange,
                    headquarters_city: _headquarters_city,
                    broad_sectors: _broad_sectors,
                    
                } )

                setOldStateFormData( { 
                    ...oldStateFormData,
                    erns_lst_rpt_date_min : formData.erns_lst_rpt_date_min,
                    erns_lst_rpt_date_max : formData.erns_lst_rpt_date_max,
                    erns_dued_min : formData.erns_dued_min,
                    erns_dued_max : formData.erns_dued_max,
                    ipo_date_min : formData.ipo_date_min,
                    ipo_date_max : formData.ipo_date_max,
                    incorporation_date_min : formData.incorporation_date_min,
                    incorporation_date_max : formData.incorporation_date_max
                } )
                
            }
        } else {   
                     
        setStateFormData({
            screen_id : selectedScreenList,
            eps_rating_min : 0,
            eps_rating_max : 0,
            rs_rating_min : 0,
            rs_rating_min : 0,
            rs_rating_max : 0,
            smr_rating : '',
            ad_rating : '',
            comp_rating_min : 0,
            comp_rating_max : 0,
            ind_group_rs_rating : '',
            erns_lst_rpt_date_min : new Date().toISOString().substring(0, 10),
            erns_lst_rpt_date_max : new Date().toISOString().substring(0, 10),
            erns_dued_min : new Date().toISOString().substring(0, 10),
            erns_dued_max : new Date().toISOString().substring(0, 10),
            eps_chg_lst_rpt_q_min : 0,
            eps_chg_lst_rpt_q_max : 0,
            eps_chg_q_1_min : 0,
            eps_chg_q_1_max : 0,
            erns_acce_lst_q_3 : "no",
            erns_stability_min : 0,
            erns_stability_max : 0,
            eps_chg_q_2_min : 0,
            eps_chg_q_2_max : 0,
            eps_chg_q_3_min : 0,
            eps_chg_q_3_max : 0,
            eps_chg_lst_rpt_q_eps_chg_lst_q_3_is_bigger : "no",
            avg_eps_chg_lst_q_2_min : 0,
            avg_eps_chg_lst_q_2_max : 0,
            avg_eps_chg_lst_q_3_min : 0,
            avg_eps_chg_lst_q_3_max : 0,
            avg_eps_chg_lst_q_4_min : 0,
            avg_eps_chg_lst_q_4_max : 0,
            avg_eps_chg_lst_q_5_min : 0,
            avg_eps_chg_lst_q_5_max : 0,
            avg_eps_chg_lst_q_6_min : 0,
            avg_eps_chg_lst_q_6_max : 0,
            eps_trailing_q_4_min : 0,
            eps_trailing_q_4_max : 0,
            eps_trailing_q_4_is_bigger : "no",
            eps_trailing_q_4_lst_y_is_bigger : "no",
            eps_chg_lst_rpty_vs_1y_ago_min : 0,
            eps_chg_lst_rpty_vs_1y_ago_max : 0,
            eps_chg_lst_rpty_vs_2y_ago_min : 0,
            eps_chg_lst_rpty_vs_2y_ago_max : 0,
            eps_chg_lst_y_min : 0,
            eps_chg_lst_y_max : 0,
            eps_grow_rate_lst_3y_min : 0,
            eps_grow_rate_lst_3y_max : 0,
            eps_grow_rate_lst_5y_min : 0,
            eps_grow_rate_lst_5y_max : 0,
            eps_grow_rate_lst_3y_5y_is_bigger : "no",
            eps_grow_rate_lst_5y_percent_rnk_min : 0,
            eps_grow_rate_lst_5y_percent_rnk_max : 0,
            eps_grow_rate_projected_sus_growth_min : 0,
            eps_grow_rate_projected_sus_growth_max : 0,
            eps_lst_rpty_min : 0,
            eps_lst_rpty_max : 0,
            eps_1y_ago_min : 0,
            eps_1y_ago_max : 0,
            eps_2y_ago_min : 0,
            eps_2y_ago_max : 0,
            eps_3y_ago_min : 0,
            eps_3y_ago_max : 0,
            eps_4y_ago_min : 0,
            eps_4y_ago_max : 0,
            eps_5y_ago_min : 0,
            eps_5y_ago_max : 0,
            eps_6y_ago_min : 0,
            eps_6y_ago_max : 0,
            eps_lst_rpty_4y_is_bigger : "no",
            eps_est_erns_surp_min : 0,
            eps_est_erns_surp_max : 0,
            eps_est_chg_next_q_min : 0,
            eps_est_chg_next_q_max : 0,
            eps_est_chg_cur_y_min : 0,
            eps_est_chg_cur_y_max : 0,
            eps_est_chg_1y_forward_vs_min : 0,
            eps_est_chg_1y_forward_vs_max : 0,
            sales_chg_lst_rpt_q_min : 0,
            sales_chg_lst_rpt_q_max : 0,
            avg_sales_chg_lst_2_q_min : 0,
            avg_sales_chg_lst_2_q_max : 0,
            avg_sales_chg_lst_3_q_min : 0,
            avg_sales_chg_lst_3_q_max : 0,
            avg_sales_chg_lst_4_q_min : 0,
            avg_sales_chg_lst_4_q_max : 0,
            avg_sales_chg_lst_5_q_min : 0,
            avg_sales_chg_lst_5_q_max : 0,
            avg_sales_chg_lst_6_q_min : 0,
            avg_sales_chg_lst_6_q_max : 0,
            sales_acc_lst_2_q : 'no',
            sales_acc_lst_3_q : 'no',
            sales_chg_lst_rpt_y_min : 0,
            sales_chg_lst_rpt_y_max : 0,
            sales_growth_rate_lst_3_y_min : 0,
            sales_growth_rate_lst_3_y_max : 0,
            sales_growth_rate_lst_5_y_min : 0,
            sales_growth_rate_lst_5_y_max : 0,
            tot_ann_sales_lst_rpt_y_min : 0,
            tot_ann_sales_lst_rpt_y_max : 0,
            company_ids_g_r_min : 0,
            company_ids_g_r_max : 0,
            industry_g_n : [],
            broad_sectors : [],
            shares_outstanding_min : 0,
            shares_outstanding_max : 0,
            shares_in_float_min : 0,
            shares_in_float_max : 0,
            market_capitialization_min : 0,
            market_capitialization_max : 0,
            enterprise_value_min : 0,
            enterprise_value_max : 0,
            sponsorship_rating : '',
            funds_min : 0,
            funds_max : 0,
            funds_increase_min : 0,
            funds_increase_max : 0,
            number_of_fund_min : 0,
            number_of_fund_max : 0,
            management_min : 0,
            management_max : 0,
            institutional_ownership : 'no',
            price_min : 0,
            price_max : 0,
            price_vs_52_week_high_min : 0,
            price_vs_52_week_high_max : 0,
            price_chg_cur_d_min : 0,
            price_chg_cur_d_max : 0,
            price_chg_min : 0,
            price_chg_max : 0,
            price_chg_cur_w_min : 0,
            price_chg_cur_w_max : 0,
            price_chg_lst_m_min : 0,
            price_chg_lst_m_max : 0,
            price_chg_lst_3_m_min : 0,
            price_chg_lst_3_m_max : 0,
            price_chg_lst_6_m_min : 0,
            price_chg_lst_6_m_max : 0,
            price_chg_lst_12_m_min : 0,
            price_chg_lst_12_m_max : 0,
            price_chg_y_to_d_min : 0,
            price_chg_y_to_d_max : 0,
            price_chg_sp_500_lst26w_min : 0,
            price_chg_sp_500_lst26w_max : 0,
            weekly_closing_range_min : 0,
            weekly_closing_range_max : 0,
            daily_closing_range_min : 0,
            daily_closing_range_max : 0,
            price_vs_10_d_min : 0,
            price_vs_10_d_max : 0,
            price_vs_21_d_min : 0,
            price_vs_21_d_max : 0,
            price_vs_50_d_min : 0,
            price_vs_50_d_max : 0,
            price_vs_150_d_min : 0,
            price_vs_150_d_max : 0,
            price_vs_200_d_min : 0,
            price_vs_200_d_max : 0,
            d_10_d_21_d_50 : 'no',
            d_50_d_150_d_200 : 'no',
            vol_50_d_avg_min : 0,
            vol_50_d_avg_max : 0,
            vol_Chg_50_d_avg_min : 0,
            vol_Chg_50_d_avg_max : 0,
            w_vol_chg_10_w_avg_min : 0,
            w_vol_chg_10_w_avg_max : 0,
            cur_d_vol_grt_pre_5_d : 'no',
            cur_d_vol_grt_pre_10_d : 'no',
            cur_d_vol_grt_pre_20_d : 'no',
            vol_int_min : 0,
            vol_int_max : 0,
            up_down_vol_rat_min : 0,
            up_down_vol_rat_max : 0,
            vol_50_d_avg_dol_1000s_min : 0,
            vol_50_d_avg_dol_1000s_max : 0,
            rs_line_new_high : 'no',
            rs_line_new_low : 'no',
            rs_rating_3_m_min : 0,
            rs_rating_3_m_max : 0,
            rs_rating_6_m_min : 0,
            rs_rating_6_m_max : 0,
            timeliness_rating : '',
            alpha_min : 0,
            alpha_max : 0,
            beta_min : 0,
            beta_max : 0,
            avg_true_range_30_d_min : 0,
            avg_true_range_30_d_max : 0,
            davidend_yield_min : 0,
            davidend_yield_max : 0,
            after_tax_mrgn_acce_lst_3_q : 'no',
            pre_tax_mrgn_lst_rpty_min : 0,
            pre_tax_mrgn_lst_rpty_max : 0,
            after_tax_mrgn_lst_rpt_q_min : 0,
            after_tax_mrgn_lst_rpt_q_max : 0,
            after_tax_mrgn_avg_lst_q_2_min : 0,
            after_tax_mrgn_avg_lst_q_2_max : 0,
            after_tax_mrgn_avg_lst_q_3_min : 0,
            after_tax_mrgn_avg_lst_q_3_max : 0,
            after_tax_mrgn_avg_lst_q_4_min : 0,
            after_tax_mrgn_avg_lst_q_4_max : 0,
            after_tax_mrgn_avg_lst_q_5_min : 0,
            after_tax_mrgn_avg_lst_q_5_max : 0,
            after_tax_mrgn_avg_lst_q_6_min : 0,
            after_tax_mrgn_avg_lst_q_6_max : 0,
            opr_sys_ids_median_is_bigger : 'no',
            profile_mrgn_ids_median_is_bigger : 'no',
            p_e_current_min : 0,
            p_e_current_max : 0,
            p_e_est_min : 0,
            p_e_est_max : 0,
            p_e_vs_sp_500_min : 0,
            p_e_vs_sp_500_max : 0,
            p_e_percent_rnk_min : 0,
            p_e_percent_rnk_max : 0,
            p_e_percent_rnk_in_grp_min : 0,
            p_e_percent_rnk_in_grp_max : 0,
            p_e_avg_5y_is_bigger : 'no',
            peg_min : 0,
            peg_max : 0,
            peg_divid_adj_min : 0,
            peg_divid_adj_max : 0,
            cf_v_eps_diff_lst_rpt_q_min : 0,
            cf_v_eps_diff_lst_rpt_q_max : 0,
            cf_v_eps_diff_lst_rpt_y_min : 0,
            cf_v_eps_diff_lst_rpt_y_max : 0,
            roe_5y_avg_min : 0,
            roe_5y_avg_max : 0,
            debit_lst_rpt_y_min : 0,
            debit_lst_rpt_y_max : 0,
            current_ratio_min : 0,
            current_ratio_max : 0,
            price_to_sales_min : 0,
            price_to_sales_max : 0,
            price_to_book_value_min : 0,
            price_to_book_value_max : 0,
            price_to_cash_flow_min : 0,
            price_to_cash_flow_max : 0,
            epr_val_free_cash_flow_min : 0,
            epr_val_free_cash_flow_max : 0,
            long_term_debit_work_cap_min : 0,
            long_term_debit_work_cap_max : 0,
            tot_lia_tot_assn : 'no',
            exchange : [],
            adr : 'no',
            etf_closed_end_fund : 'no',
            etf : 'no',
            options : 'no',
            ipo_date_min : new Date().toISOString().substring(0, 10),
            ipo_date_max : new Date().toISOString().substring(0, 10),
            incorporation_date_min : new Date().toISOString().substring(0, 10),
            incorporation_date_max : new Date().toISOString().substring(0, 10),
            headquarters_city : [],
            new_ceo_in_lst_12_m : 'no',
            ibd_article_lst_2_y : 'no',
            ibd_50 : 'no',
            ibd_new_america : 'no',
            ibd_85 : 'no',
            ibd_big_cap_20 : 'no',
        })              
        
        setOldStateFormData({
            screen_id : selectedScreenList,
            eps_rating_min : 0,
            eps_rating_max : 0,
            rs_rating_min : 0,
            rs_rating_min : 0,
            rs_rating_max : 0,
            smr_rating : '',
            ad_rating : '',
            comp_rating_min : 0,
            comp_rating_max : 0,
            ind_group_rs_rating : '',
            erns_lst_rpt_date_min : new Date().toISOString().substring(0, 10),
            erns_lst_rpt_date_max : new Date().toISOString().substring(0, 10),
            erns_dued_min : new Date().toISOString().substring(0, 10),
            erns_dued_max : new Date().toISOString().substring(0, 10),
            eps_chg_lst_rpt_q_min : 0,
            eps_chg_lst_rpt_q_max : 0,
            eps_chg_q_1_min : 0,
            eps_chg_q_1_max : 0,
            erns_acce_lst_q_3 : "no",
            erns_stability_min : 0,
            erns_stability_max : 0,
            eps_chg_q_2_min : 0,
            eps_chg_q_2_max : 0,
            eps_chg_q_3_min : 0,
            eps_chg_q_3_max : 0,
            eps_chg_lst_rpt_q_eps_chg_lst_q_3_is_bigger : "no",
            avg_eps_chg_lst_q_2_min : 0,
            avg_eps_chg_lst_q_2_max : 0,
            avg_eps_chg_lst_q_3_min : 0,
            avg_eps_chg_lst_q_3_max : 0,
            avg_eps_chg_lst_q_4_min : 0,
            avg_eps_chg_lst_q_4_max : 0,
            avg_eps_chg_lst_q_5_min : 0,
            avg_eps_chg_lst_q_5_max : 0,
            avg_eps_chg_lst_q_6_min : 0,
            avg_eps_chg_lst_q_6_max : 0,
            eps_trailing_q_4_min : 0,
            eps_trailing_q_4_max : 0,
            eps_trailing_q_4_is_bigger : "no",
            eps_trailing_q_4_lst_y_is_bigger : "no",
            eps_chg_lst_rpty_vs_1y_ago_min : 0,
            eps_chg_lst_rpty_vs_1y_ago_max : 0,
            eps_chg_lst_rpty_vs_2y_ago_min : 0,
            eps_chg_lst_rpty_vs_2y_ago_max : 0,
            eps_chg_lst_y_min : 0,
            eps_chg_lst_y_max : 0,
            eps_grow_rate_lst_3y_min : 0,
            eps_grow_rate_lst_3y_max : 0,
            eps_grow_rate_lst_5y_min : 0,
            eps_grow_rate_lst_5y_max : 0,
            eps_grow_rate_lst_3y_5y_is_bigger : "no",
            eps_grow_rate_lst_5y_percent_rnk_min : 0,
            eps_grow_rate_lst_5y_percent_rnk_max : 0,
            eps_grow_rate_projected_sus_growth_min : 0,
            eps_grow_rate_projected_sus_growth_max : 0,
            eps_lst_rpty_min : 0,
            eps_lst_rpty_max : 0,
            eps_1y_ago_min : 0,
            eps_1y_ago_max : 0,
            eps_2y_ago_min : 0,
            eps_2y_ago_max : 0,
            eps_3y_ago_min : 0,
            eps_3y_ago_max : 0,
            eps_4y_ago_min : 0,
            eps_4y_ago_max : 0,
            eps_5y_ago_min : 0,
            eps_5y_ago_max : 0,
            eps_6y_ago_min : 0,
            eps_6y_ago_max : 0,
            eps_lst_rpty_4y_is_bigger : "no",
            eps_est_erns_surp_min : 0,
            eps_est_erns_surp_max : 0,
            eps_est_chg_next_q_min : 0,
            eps_est_chg_next_q_max : 0,
            eps_est_chg_cur_y_min : 0,
            eps_est_chg_cur_y_max : 0,
            eps_est_chg_1y_forward_vs_min : 0,
            eps_est_chg_1y_forward_vs_max : 0,
            sales_chg_lst_rpt_q_min : 0,
            sales_chg_lst_rpt_q_max : 0,
            avg_sales_chg_lst_2_q_min : 0,
            avg_sales_chg_lst_2_q_max : 0,
            avg_sales_chg_lst_3_q_min : 0,
            avg_sales_chg_lst_3_q_max : 0,
            avg_sales_chg_lst_4_q_min : 0,
            avg_sales_chg_lst_4_q_max : 0,
            avg_sales_chg_lst_5_q_min : 0,
            avg_sales_chg_lst_5_q_max : 0,
            avg_sales_chg_lst_6_q_min : 0,
            avg_sales_chg_lst_6_q_max : 0,
            sales_acc_lst_2_q : 'no',
            sales_acc_lst_3_q : 'no',
            sales_chg_lst_rpt_y_min : 0,
            sales_chg_lst_rpt_y_max : 0,
            sales_growth_rate_lst_3_y_min : 0,
            sales_growth_rate_lst_3_y_max : 0,
            sales_growth_rate_lst_5_y_min : 0,
            sales_growth_rate_lst_5_y_max : 0,
            tot_ann_sales_lst_rpt_y_min : 0,
            tot_ann_sales_lst_rpt_y_max : 0,
            company_ids_g_r_min : 0,
            company_ids_g_r_max : 0,
            industry_g_n : [],
            broad_sectors : [],
            shares_outstanding_min : 0,
            shares_outstanding_max : 0,
            shares_in_float_min : 0,
            shares_in_float_max : 0,
            market_capitialization_min : 0,
            market_capitialization_max : 0,
            enterprise_value_min : 0,
            enterprise_value_max : 0,
            sponsorship_rating : '',
            funds_min : 0,
            funds_max : 0,
            funds_increase_min : 0,
            funds_increase_max : 0,
            number_of_fund_min : 0,
            number_of_fund_max : 0,
            management_min : 0,
            management_max : 0,
            institutional_ownership : 'no',
            price_min : 0,
            price_max : 0,
            price_vs_52_week_high_min : 0,
            price_vs_52_week_high_max : 0,
            price_chg_cur_d_min : 0,
            price_chg_cur_d_max : 0,
            price_chg_min : 0,
            price_chg_max : 0,
            price_chg_cur_w_min : 0,
            price_chg_cur_w_max : 0,
            price_chg_lst_m_min : 0,
            price_chg_lst_m_max : 0,
            price_chg_lst_3_m_min : 0,
            price_chg_lst_3_m_max : 0,
            price_chg_lst_6_m_min : 0,
            price_chg_lst_6_m_max : 0,
            price_chg_lst_12_m_min : 0,
            price_chg_lst_12_m_max : 0,
            price_chg_y_to_d_min : 0,
            price_chg_y_to_d_max : 0,
            price_chg_sp_500_lst26w_min : 0,
            price_chg_sp_500_lst26w_max : 0,
            weekly_closing_range_min : 0,
            weekly_closing_range_max : 0,
            daily_closing_range_min : 0,
            daily_closing_range_max : 0,
            price_vs_10_d_min : 0,
            price_vs_10_d_max : 0,
            price_vs_21_d_min : 0,
            price_vs_21_d_max : 0,
            price_vs_50_d_min : 0,
            price_vs_50_d_max : 0,
            price_vs_150_d_min : 0,
            price_vs_150_d_max : 0,
            price_vs_200_d_min : 0,
            price_vs_200_d_max : 0,
            d_10_d_21_d_50 : 'no',
            d_50_d_150_d_200 : 'no',
            vol_50_d_avg_min : 0,
            vol_50_d_avg_max : 0,
            vol_Chg_50_d_avg_min : 0,
            vol_Chg_50_d_avg_max : 0,
            w_vol_chg_10_w_avg_min : 0,
            w_vol_chg_10_w_avg_max : 0,
            cur_d_vol_grt_pre_5_d : 'no',
            cur_d_vol_grt_pre_10_d : 'no',
            cur_d_vol_grt_pre_20_d : 'no',
            vol_int_min : 0,
            vol_int_max : 0,
            up_down_vol_rat_min : 0,
            up_down_vol_rat_max : 0,
            vol_50_d_avg_dol_1000s_min : 0,
            vol_50_d_avg_dol_1000s_max : 0,
            rs_line_new_high : 'no',
            rs_line_new_low : 'no',
            rs_rating_3_m_min : 0,
            rs_rating_3_m_max : 0,
            rs_rating_6_m_min : 0,
            rs_rating_6_m_max : 0,
            timeliness_rating : '',
            alpha_min : 0,
            alpha_max : 0,
            beta_min : 0,
            beta_max : 0,
            avg_true_range_30_d_min : 0,
            avg_true_range_30_d_max : 0,
            davidend_yield_min : 0,
            davidend_yield_max : 0,
            after_tax_mrgn_acce_lst_3_q : 'no',
            pre_tax_mrgn_lst_rpty_min : 0,
            pre_tax_mrgn_lst_rpty_max : 0,
            after_tax_mrgn_lst_rpt_q_min : 0,
            after_tax_mrgn_lst_rpt_q_max : 0,
            after_tax_mrgn_avg_lst_q_2_min : 0,
            after_tax_mrgn_avg_lst_q_2_max : 0,
            after_tax_mrgn_avg_lst_q_3_min : 0,
            after_tax_mrgn_avg_lst_q_3_max : 0,
            after_tax_mrgn_avg_lst_q_4_min : 0,
            after_tax_mrgn_avg_lst_q_4_max : 0,
            after_tax_mrgn_avg_lst_q_5_min : 0,
            after_tax_mrgn_avg_lst_q_5_max : 0,
            after_tax_mrgn_avg_lst_q_6_min : 0,
            after_tax_mrgn_avg_lst_q_6_max : 0,
            opr_sys_ids_median_is_bigger : 'no',
            profile_mrgn_ids_median_is_bigger : 'no',
            p_e_current_min : 0,
            p_e_current_max : 0,
            p_e_est_min : 0,
            p_e_est_max : 0,
            p_e_vs_sp_500_min : 0,
            p_e_vs_sp_500_max : 0,
            p_e_percent_rnk_min : 0,
            p_e_percent_rnk_max : 0,
            p_e_percent_rnk_in_grp_min : 0,
            p_e_percent_rnk_in_grp_max : 0,
            p_e_avg_5y_is_bigger : 'no',
            peg_min : 0,
            peg_max : 0,
            peg_divid_adj_min : 0,
            peg_divid_adj_max : 0,
            cf_v_eps_diff_lst_rpt_q_min : 0,
            cf_v_eps_diff_lst_rpt_q_max : 0,
            cf_v_eps_diff_lst_rpt_y_min : 0,
            cf_v_eps_diff_lst_rpt_y_max : 0,
            roe_5y_avg_min : 0,
            roe_5y_avg_max : 0,
            debit_lst_rpt_y_min : 0,
            debit_lst_rpt_y_max : 0,
            current_ratio_min : 0,
            current_ratio_max : 0,
            price_to_sales_min : 0,
            price_to_sales_max : 0,
            price_to_book_value_min : 0,
            price_to_book_value_max : 0,
            price_to_cash_flow_min : 0,
            price_to_cash_flow_max : 0,
            epr_val_free_cash_flow_min : 0,
            epr_val_free_cash_flow_max : 0,
            long_term_debit_work_cap_min : 0,
            long_term_debit_work_cap_max : 0,
            tot_lia_tot_assn : 'no',
            exchange : [],
            adr : 'no',
            etf_closed_end_fund : 'no',
            etf : 'no',
            options : 'no',
            ipo_date_min : new Date().toISOString().substring(0, 10),
            ipo_date_max : new Date().toISOString().substring(0, 10),
            incorporation_date_min : new Date().toISOString().substring(0, 10),
            incorporation_date_max : new Date().toISOString().substring(0, 10),
            headquarters_city : [],
            new_ceo_in_lst_12_m : 'no',
            ibd_article_lst_2_y : 'no',
            ibd_50 : 'no',
            ibd_new_america : 'no',
            ibd_85 : 'no',
            ibd_big_cap_20 : 'no',
        })
        }           
    }, [formData])
    

    return (
        <Box className={classes.root}>
            <Grid container>
                <Grid item xs={8}>
                    <Grid container sx={{border : '2px solid #f7810b'}}>
                        <Grid item xs={4}>
                            <Category 
                                setSelectedItem={setSelectedItem}
                                selectedItem={selectedItem}
                            />
                        </Grid>
                        <Grid item xs={8}>
                            <Criteria 
                                selectedItem={selectedItem}
                                stateFormData={stateFormData}
                                setStateFormData={setStateFormData}
                                selectedScreenList={selectedScreenList}
                            />
                        </Grid>
                    </Grid>                    
                </Grid>
                <Grid item xs={4}>
                    <Summary 
                        selectedItem={selectedItem}
                        stateFormData={stateFormData}
                        oldStateFormData={oldStateFormData}
                        selectedScreenList={selectedScreenList}
                    />
                </Grid>
            </Grid>
        </Box>
    );
}

const mapStateToProps = state => ({
    formData : state.screenOption.formData,
    inserFormData : state.screenOption.inserFormData
})
const mapDispatchToProps = {
}

export default connect(mapStateToProps, mapDispatchToProps) (ScreenOption);